### ISSUE TITLE
paper question about Your  Work on RADCoT

### ISSUE THREAD

**Issue by Crownzz** [ZIZUN/RADCoT#1]
Dear RADCoT's author,

I recently came across your RADCoT project on GitHub, and I was truly impressed by the innovative approach and the results you have achieved. Your work stands out as a significant contribution to the field, and I am very interested in delving deeper into the methodologies and insights behind your model.

I am particularly keen on understanding the intricacies of your model and the underlying principles that guide its performance. If possible, could you kindly share the PDF file of any associated research paper or a detailed model diagram? Access to these resources would greatly enhance my understanding and appreciation of your work.

Thank you very much for your time and for sharing your valuable research. I look forward to your reply and any materials you could provide.

Best regards,

Lean.at a1452359372@gmail.com

**Comment by Crownzz** [comment]
If possible, please provide more details about the model structure and how the dataset is constructed.

**Comment by ZIZUN** [comment]
Thank you for showing interest in my research. I am currently in the process of finalizing the camera-ready version of this paper, and I will share it with you via email when it is completed. Next figure shows RADCoT main process. Thank you!
![image](https://github.com/ZIZUN/RADCoT/assets/24732802/e3cdef94-b77c-4b67-91ef-46ea85ae9915)

**Comment by Crownzz** [comment]
First and foremost, I would like to express my sincere gratitude for sharing the RADCoT model. Your work has significantly contributed to my research and has been immensely helpful.

I am reaching out to inquire about the dataset construction aspect associated with the RADCoT model. While attempting to implement your code, I encountered some challenges regarding dataset setup and would greatly appreciate your guidance.

Could you kindly provide a few examples of the datasets used? This information would greatly aid me in understanding the required structure and format, ensuring accurate replication and application of the model.

Additionally, I am keenly interested in the further developments and updates of your work. I would be grateful if you could notify me once the paper is finalized and published.

Thank you once again for your invaluable contribution to the community and for your assistance.

**Comment by ZIZUN** [comment]
@Crownzz  I send you a email with paper pdf file.
